import { Checkbox, Button } from "@mui/material";
import { Trash2 } from "lucide-react";

export default function TaskList({ tasks, onUpdateTask, onDeleteTask }) {
  // Define priority colors
  const priorityColors = {
    low: "bg-red-100",
    medium: "bg-yellow-100",
    high: "bg-green-100",
  };

  return (
    <div className="min-h-screen bg-[#F5F3FF] px-4 py-6">
      {/* Legend for Priority Colors */}
      <div className="mb-4 p-3 rounded-lg border bg-white shadow-sm">
        <p className="font-semibold">Priority generated by AI Agent:</p>
        <div className="flex gap-4 mt-2">
          <span className="px-3 py-1 rounded bg-red-100">Low</span>
          <span className="px-3 py-1 rounded bg-yellow-100">Medium</span>
          <span className="px-3 py-1 rounded bg-green-100">High</span>
        </div>
      </div>

      {tasks.map((task) => (
        <div
          key={task.id}
          className={`flex items-center justify-between rounded-lg border p-4 shadow-sm mb-5 ${priorityColors[task.priority] || "bg-white"}`}
        >
          <div className="flex items-center gap-3">
            <Checkbox
              checked={task.completed}
              onChange={(e) => onUpdateTask(task.id, e.target.checked)}
            />
            <span className={task.completed ? "text-muted-foreground line-through" : ""}>
              {task.title}
            </span>
          </div>
          <Button variant="ghost" size="icon" onClick={() => onDeleteTask(task.id)}>
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      ))}
    </div>
  );
}
